# **Converter format ".xlsx" en ".csv" et enregistrer dans repertoire "Output"**

In [75]:
import pandas as pd
import os

# Define the paths to the input files
comments_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Comments.xlsx"
posts_path = "/kaggle/input/comments-posts-ooredoo-djezzy-mobilis/Posts.xlsx"

# Define the output directory (working directory)
output_dir = "./"

# Read the Excel files
comments_df = pd.read_excel(comments_path)
posts_df = pd.read_excel(posts_path)

# Define the output file paths
comments_csv_path = os.path.join(output_dir, "Comments.csv")
posts_csv_path = os.path.join(output_dir, "Posts.csv")

# Save the DataFrames to CSV
comments_df.to_csv(comments_csv_path, index=False)
posts_df.to_csv(posts_csv_path, index=False)

print(f"Files have been saved to {output_dir}")

Files have been saved to ./

In [76]:
# Chemin de fichier CSV
posts_csv_path = "/kaggle/working/Posts.csv"

# Lire le fichier CSV dans de DataFrame
posts_df = pd.read_csv(posts_csv_path)

# Afficher les premières lignes pour vérifier
print("\nPosts DataFrame:")
posts_df

Posts DataFrame:

,ID,Contents,Lien Post,Nb Like,Nb Love,Nb Care,Nb Wow,Nb Sad,Nb Angry,Nb Haha,Company,Date
0,1,جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...,https://www.facebook.com/djezzy/posts/78822751...,272,45,0,1,1,76,14,Djezzy,2024-01-01
1,2,راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...,https://www.facebook.com/watch/?v=106882928102...,255,28,0,1,0,12,31,Djezzy,2024-01-04
2,3,It's Time To be a legend,https://www.facebook.com/djezzy/posts/39256499...,257,51,2,0,0,2,8,Djezzy,2024-01-10
3,4,Djezzy vous souhaite Yennayer amervuh! ⴰⵙⵙⴻⴳⴰ...,https://www.facebook.com/share/p/19UDNBoQ1k/,621,231,10,3,0,1,300,Djezzy,2024-01-11
4,5,قريباً ...,https://www.facebook.com/share/v/12B9LZySBRe/,288,49,4,0,0,3,24,Djezzy,2024-01-12
...,...,...,...,...,...,...,...,...,...,...,...,...
178,179,إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...,https://www.facebook.com/share/p/1KGHZQuXex/,208,46,6,0,0,0,1,Ooredoo,2024-03-26
179,180,مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...,https://www.facebook.com/share/v/1Bc7FtdDPx/,625,125,14,0,1,1,1,Ooredoo,2024-03-27
180,181,عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...,https://www.facebook.com/reel/954679512980806,280,40,7,1,1,0,0,Ooredoo,2024-03-28
181,182,ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...,https://www.facebook.com/watch/?v=193245186050...,148,35,3,0,0,2,0,Ooredoo,2024-03-28
182,183,أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...,https://www.facebook.com/OoredooDZ/posts/44139...,215,46,5,0,0,1,0,Ooredoo,2024-03-30

In [77]:
import pandas as pd

# Chemin de fichier CSV
comments_csv_path = "/kaggle/working/Comments.csv"

# Lire les fichiers CSV dans des DataFrames
comments_df = pd.read_csv(comments_csv_path)

# Afficher les premières lignes pour vérifier
print("Comments DataFrame:")
comments_df

Comments DataFrame:

,ID Post,User Name,Comments
0,1,Samir Bekhouche,NaN
1,1,Yanise Yanise,سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2,1,Jj Kie,كل عام و انتم بخير
3,1,Sakou Younes,كل عام وأنتم بخير
4,1,راني نعاني,كل عام وحنا بخير
...,...,...,...
4571,183,Ĺã Rõsë Ýb,❤️❤️
4572,183,نسمات هادئة,💕💕💕💕
4573,183,ملك ملهاش غيرك,❤❤❤❤❤❤🌹
4574,183,سعيدي رضا,NaN
4575,183,جيبلي فيت فيت,❤️❤️❤️❤️

In [78]:
posts_df["Contents"]

0      جازي تتمنّى لكم سنة سعيدة🥰\n#DJEZZY #HAPPY_NEW...
1      راك en panne و خصك رصيد ؟\nمع خدمة Tranquilo ت...
2                               It's Time To be a legend
3      Djezzy vous souhaite Yennayer amervuh!  ⴰⵙⵙⴻⴳⴰ...
4                                             قريباً ...
                             ...
178    إثارة الألعاب تتعاش مع الأحباب، خاصة كي Ooredo...
179    مع Ooredoo ديما رابحين !\nوجّدنا لكم حاجة جديد...
180    عشنا مع بعض أجواء رمضانية رائعة من خلال الإفطا...
181    ضاعفوا اشتراك الإنترنت الخاص بكم خلال شهر رمضا...
182    أنتم من عشاق السينما العربية؟ حمّلوا التطبيق ش...
Name: Contents, Length: 183, dtype: object

In [79]:
comments_df["Comments"]

0                                                     NaN
1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
                              ...
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4574                                                  NaN
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4576, dtype: object

# **Pretraitement**

## **Bibiliothèques**

In [80]:
import pandas as pd
import re
import emoji
import warnings

## **Suppression des valeurs NaN "Comments"**

In [81]:
comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [82]:
comments_df["Comments"]

1       سلام عليكم ورحمة لديا مشكلة ! فليكسيت 100 دج و...
2                                      كل عام و انتم بخير
3                                       كل عام وأنتم بخير
4                                        كل عام وحنا بخير
5                                        كل عام وحنا بخير
                              ...
4570                                               🩷🩷🩷🩷🩷🩷
4571                                                 ❤️❤️
4572                                                 💕💕💕💕
4573                                              ❤❤❤❤❤❤🌹
4575                                             ❤️❤️❤️❤️
Name: Comments, Length: 4396, dtype: object

## **Transformation Aransia en dialectique**

#### Translittérer d’une langue ou d’un dialecteè un autre : Nous avons utilisé le module Aransia pour transformer les phrases de la langue francais en langue dialectique arabe

In [83]:
!pip install aaransia emoji

Requirement already satisfied: aaransia in /usr/local/lib/python3.10/dist-packages (1.1)
Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (2.14.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from aaransia) (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from aaransia) (1.26.4)
Requirement already satisfied: unidecode in /usr/local/lib/python3.10/dist-packages (from aaransia) (1.3.8)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.10/dist-packages (from numpy->aaransia) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.10/dist-packages (from numpy->aaransia) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.10/dist-packages (from numpy->aaransia) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.10/dist-packages (from numpy->aaransia) (2025.0.1)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.10/dist-packages (from numpy->aaransia) (2022.0.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.10/dist-packages (from numpy->aaransia) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->aaransia) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->aaransia) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->aaransia) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->aaransia) (1.17.0)
Requirement already satisfied: intel-openmp>=2024 in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->aaransia) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.10/dist-packages (from mkl->numpy->aaransia) (2022.0.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.10/dist-packages (from tbb==2022.*->mkl->numpy->aaransia) (1.2.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.10/dist-packages (from mkl_umath->numpy->aaransia) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.10/dist-packages (from intel-openmp>=2024->mkl->numpy->aaransia) (2024.2.0)

In [ ]:
from aaransia import transliterate, SourceLanguageError
warnings.simplefilter('ignore')

def transform_aransia(text):
    try:
        return transliterate(text, source='fr', target='ar')
    except SourceLanguageError:
        return text  # Retourne le texte original en cas d'erreur

# Appliquer la transformation aux colonnes concernées
comments_df["Comments"] = comments_df["Comments"].astype(str).apply(transform_aransia)
posts_df["Contents"] = posts_df["Contents"].astype(str).apply(transform_aransia)

In [ ]:
# Affichage d'un exemple après le premier prétraitement
print("Exemple après translittération (Comments):")
comments_df["Comments"]

In [ ]:
print("Exemple après translittération (Contents):")
posts_df["Contents"]

In [ ]:
def normalize_arabic(text):
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("گ", "ك", text)
    return text

# Appliquer la normalisation
comments_df["Comments"] = comments_df["Comments"].apply(normalize_arabic)
posts_df["Contents"] = posts_df["Contents"].apply(normalize_arabic)

In [ ]:
comments_df["Comments"]

In [ ]:
posts_df["Contents"]

# **Nettoyage des données**

In [ ]:
def clean_text(text):
    text = emoji.replace_emoji(text, replace='')  # Supprimer les emojis
    text = re.sub(r'http\S+ | htps\S+', '', str(text))  # Supprimer les hyperliens
    text = re.sub(r'((www\.[^\s]+)|(https?://[^\s]+))', '', str(text))  # Supprimer les URL
    text = re.sub(r'@\S+', '', str(text))  # Supprimer les mots commençant par @
    text = text.replace("_", " ").replace("#", "")  # Supprimer # et _
    text = re.sub(r'\. | , | ، | ؛', ' ', text)  # Remplacer certaines ponctuations
    text = re.sub(r'\bRT\b | \bRetweeted\b', '', text)  # Supprimer les mots réservés
    text = re.sub(r'[\u0660-\u0669\u06F0-\u06F9]+', '', text)  # Supprimer chiffres arabes
    text = re.sub(r"(.)\1{2,}", r"\1", text)  # Supprimer les caractères consécutifs en double
    text = re.sub('\d+', ' ', text)  # Supprimer les chiffres
    text = text.replace('\n', ' ').replace('/', ' ')  # Supprimer sauts de ligne et /
    text = re.sub(r'[^\w\s]', '', text)  # Supprimer les caractères spéciaux
    return text.strip()

comments_df["Comments"] = comments_df["Comments"].apply(clean_text)
posts_df["Contents"] = posts_df["Contents"].apply(clean_text)

# Remplacer les valeurs nulles par une chaîne vide
comments_df["Comments"].fillna('', inplace=True)
posts_df["Contents"].fillna('', inplace=True)

comments_df = comments_df.dropna(subset=["Comments"])
comments_df = comments_df[comments_df["Comments"].str.strip() != ""]

In [ ]:
posts_df["Contents"]

In [ ]:
comments_df["Comments"]

# **Stop word**

Les Stop words ou bien les mots vides sont les mots couramment utilisés qui sont généralement ignorés par le moteur de recherche, tels que the, اللذين, إن, etc. Ces mots sont supprimés pour économiser de l’espace dans la base de données et le temps de traitement, c’est pour cette raison qu’on va essayer dans l’étape suivante d’utiliser le package ntlk pour supprimer ces mots vides.

Le package stop-words est utilisé pour supprimer les mots vides du texte en Python. Ce paquet contient des mots vides dans de nombreuses langues comme l’anglais, l’Arabe, le français, l’espagnol et plus encore.

In [ ]:
# import necessary libraries
import nltk
from nltk.corpus import stopwords

# Charger les stopwords pour l'arabe et le français
nltk.download('stopwords')
arabic_stopwords = set(stopwords.words('arabic'))
french_stopwords = set(stopwords.words('french'))

In [ ]:
# Affiche quelques mots (stop-words)
print(stopwords.words('arabic'))

In [ ]:
def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in arabic_stopwords and word not in french_stopwords]
    return " ".join(filtered_words)

# Appliquer la suppression des stop-words
comments_df["Comments"] = comments_df["Comments"].apply(remove_stopwords)
posts_df["Contents"] = posts_df["Contents"].apply(remove_stopwords)

In [ ]:
posts_df["Contents"]

In [ ]:
comments_df["Comments"]

## **Correction des abréviations**

In [ ]:
abbreviations = {
    "cnx": "connexion",
    "mrc": "merci",
    "num": "numéro"
    # Ajoutez d'autres abréviations ici
}

def replace_abbreviations(text):
    words = text.split()
    return ' '.join([abbreviations[word] if word in abbreviations else word for word in words])

comments_df['Comments'] = comments['Comments'].apply(replace_abbreviations)
posts_df['Contents'] = posts['Contents'].apply(replace_abbreviations)

## **Sauvegarde des fichiers nettoyés**

In [ ]:
# Sauvegarder les fichiers après la translittération
comments_df.to_csv("Comments_clean.csv", index=False)
posts_df.to_csv("Posts_clean.csv", index=False)

print("Prétraitement terminé et fichiers enregistrés !")